"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, Heart, Leaf, LockKeyhole, Mic2, MoreHorizontal, ShieldCheck, Wind } from "lucide-react";
import { useAppStore } from "@/store/useAppStore";
import { caseService } from "@/services/case";
import { CaseRecord } from "@/types";
import { formatDate } from "@/lib/utils";
import { TAARA } from "@/components/TAARA";

const moods = [{ label: "A little heavy", icon: "◌", tone: "bg-[#e6f1ee] text-[#227d76]" }, { label: "Somewhat heavy", icon: "◒", tone: "bg-[#fff1dc] text-[#bd7927]" }, { label: "Very heavy", icon: "●", tone: "bg-[#f7e4df] text-[#ac6353]" }, { label: "I’m feeling okay", icon: "○", tone: "bg-[#e5eddc] text-[#628062]" }];

export default function SurvivorHomePage() {
  const { victimToken, survivorName } = useAppStore();
  const [caseRecord, setCaseRecord] = useState<CaseRecord | null>(null);
  const [selectedMood, setSelectedMood] = useState<string | null>(null);
  useEffect(() => { if (victimToken) caseService.getCase(victimToken).then(setCaseRecord); else caseService.getCase("VIC_8291").then(setCaseRecord); }, [victimToken]);
  const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening";
  const displayName = survivorName ?? caseRecord?.survivorName ?? "Sunita";

  return <div className="px-5 pb-8 md:px-10 md:pb-14 xl:px-14"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div className="saath-fade"><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#7f928a] md:hidden">Your space</p><h1 className="font-display text-[42px] leading-[.98] text-[#172326] md:text-[56px]">{greeting}, {displayName}</h1><p className="mt-4 text-lg text-[#63736e]">You&apos;re here. <span className="font-display italic text-[#0f766e]">That&apos;s enough.</span></p></div><div className="hidden items-center gap-2 text-xs text-[#6c7c77] md:flex"><span className="h-2 w-2 rounded-full bg-[#7faf86]" /> Your space is private and consent-first</div></div>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(330px,.75fr)]"><section className="space-y-5"><div className="surface saath-fade overflow-hidden rounded-[28px] p-6 md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#7e918b]">A small check-in</p><h2 className="mt-3 font-display text-3xl text-[#172326] md:text-[36px]">How are things feeling today?</h2><p className="mt-2 text-sm text-[#71817c]">There are no right or wrong answers. Just notice what is true.</p></div><div className="hidden h-12 w-12 items-center justify-center rounded-2xl bg-[#f4f6ec] text-[#0f766e] md:flex"><Heart size={21} /></div></div><div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{moods.map((mood) => <button key={mood.label} onClick={() => setSelectedMood(mood.label)} className={`group rounded-2xl border p-4 text-left ${selectedMood === mood.label ? "border-[#0f766e] bg-[#eef8f3] ring-4 ring-[#0f766e]/8" : "border-[#dce4df] bg-[#fffdf9] hover:-translate-y-0.5 hover:border-[#8bc2b2]"}`}><span className={`mb-5 inline-flex h-10 w-10 items-center justify-center rounded-full text-lg ${mood.tone}`}>{mood.icon}</span><span className="block text-sm font-semibold leading-tight text-[#334541]">{mood.label}</span>{selectedMood === mood.label && <span className="mt-2 flex items-center gap-1 text-[11px] font-bold text-[#0f766e]"><Check size={13} /> Saved</span>}</button>)}</div>{selectedMood && <div className="mt-5 flex items-center justify-between rounded-2xl bg-[#f4f6ec] px-4 py-3 text-sm text-[#51615d]"><span>Thank you for sharing. Would you like a little more space to reflect?</span><Link href="/survivor/check-in" className="ml-3 whitespace-nowrap font-bold text-[#0f766e]">Continue <ArrowRight className="ml-1 inline" size={14} /></Link></div>}</div>
      <div className="grid grid-cols-1 gap-5 md:grid-cols-2"><Link href="/survivor/taara" className="surface-soft group rounded-[26px] p-6 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-xl text-[#d69e2e] shadow-sm">✦</div><ArrowRight size={18} className="text-[#8da19a] transition-transform group-hover:translate-x-1" /></div><h3 className="mt-6 font-display text-2xl text-[#253631]">Something for you</h3><p className="mt-2 text-sm leading-relaxed text-[#65746f]">Take two minutes to slow down with a gentle grounding activity.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-[#0f766e]"><Wind size={15} /> 2 min activity</div></Link><Link href="/survivor/check-in" className="surface-soft group rounded-[26px] bg-[#fff4e9] p-6 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-[#b97942] shadow-sm"><Mic2 size={19} /></div><ArrowRight size={18} className="text-[#a98a77] transition-transform group-hover:translate-x-1" /></div><h3 className="mt-6 font-display text-2xl text-[#503d31]">Check in your way</h3><p className="mt-2 text-sm leading-relaxed text-[#7e6656]">Text, voice, or IVRS. Choose what feels most comfortable today.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-[#a96737]"><Clock3 size={15} /> Whenever you&apos;re ready</div></Link></div></section>
      <aside className="space-y-5"><TAARA /><div className="surface rounded-[26px] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8a9b94]">Your case</p><p className="mt-2 font-mono text-sm font-semibold text-[#203530]">{caseRecord?.docket ?? "NHAA-RJ-2026-004821"}</p></div><Link href="/survivor/case" aria-label="View case" className="rounded-full p-2 text-[#7c8d86] hover:bg-[#f4f6ec] hover:text-[#0f766e]"><MoreHorizontal size={18} /></Link></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#eef6ef] p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#d2e9d5] text-[#488056]"><Leaf size={17} /></span><div><p className="text-sm font-semibold text-[#3f604a]">Investigation in progress</p><p className="mt-0.5 text-xs text-[#718879]">Your support team is with you</p></div></div><div className="mt-5 flex items-center justify-between border-t border-[#e3e9e4] pt-4"><div className="flex items-center gap-2 text-xs text-[#72827c]"><CalendarDays size={15} /> Next hearing</div><span className="text-sm font-bold text-[#334a42]">{caseRecord?.nextHearingDate ? formatDate(caseRecord.nextHearingDate) : "18 September"}</span></div><Link href="/survivor/case" className="mt-5 flex items-center justify-between text-sm font-bold text-[#0f766e]">View my case <ChevronRight size={16} /></Link></div><div className="flex items-center gap-3 px-2 text-xs leading-relaxed text-[#7a8984]"><ShieldCheck size={16} className="shrink-0 text-[#7faf86]" /> Your choices, consent, and privacy controls are always visible.</div><div className="flex items-center gap-2 px-2 text-xs text-[#8b9792]"><LockKeyhole size={13} /> Synthetic demonstration data · SAATH prototype</div></aside></div>
  </div>;
}
