import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
import { env } from '../config/env.js';
import type { CaseRecord, OtpChallenge, TimelineEvent } from '../types/domain.js';

export interface Store { otp: Map<string, OtpChallenge>; cases: CaseRecord[]; timelines: TimelineEvent[]; users: Map<string, any>; records: Map<string, any[]>; blocklist: Set<string>; }
const demoCase: CaseRecord = { id:'case-demo-001', docket:'NHAA-RJ-2026-004821', victimToken:'VIC_DEMO_8291', survivorName:'Asha (demo)', registeredPhone:'+919876543210', registrationDate:'2026-01-18', state:'Rajasthan', district:'Jaipur', caseCategory:'Witness protection and rehabilitation', incidentDate:'2025-12-11', currentStage:'Investigation', firStatus:'Registered', investigationStatus:'In progress', chargesheetStatus:'Pending', nextHearingDate:'2026-10-14', hearingCount:2, adjournmentCount:0, compensationStatus:'Pending', compensationAmountApproved:250000, compensationAmountReceived:0, protectionStatus:'Under review', relocationStatus:'Not requested', legalAidStatus:'Assigned', rehabilitationStatus:'Support plan active', counsellorAssigned:'demo-counsellor-001', preferredLanguage:'English' };
export const memoryStore: Store = { otp:new Map(), cases:[demoCase], timelines:[{id:'event-1',caseId:demoCase.id,date:'2026-01-18',type:'case',label:'Case registered'},{id:'event-2',caseId:demoCase.id,date:'2026-02-02',type:'support',label:'Legal aid assigned'},{id:'event-3',caseId:demoCase.id,date:'2026-03-12',type:'wellbeing',label:'First voluntary check-in'}],users:new Map(),records:new Map(),blocklist:new Set() };
export const supabase: SupabaseClient | null = env.SUPABASE_URL && (env.SUPABASE_SECRET_KEY || env.SUPABASE_PUBLISHABLE_KEY) ? createClient(env.SUPABASE_URL, env.SUPABASE_SECRET_KEY || env.SUPABASE_PUBLISHABLE_KEY!, { auth:{autoRefreshToken:false,persistSession:false} }) : null;
export const store: Store = memoryStore;
export const id = () => randomUUID();
export async function supabaseInsert(table:string, payload:Record<string,unknown>) { if (env.DATA_MODE !== 'supabase' || !supabase) return null; const {data,error}=await supabase.from(table).insert(payload).select().single(); if(error) throw error; return data; }
export async function supabaseSelect(table:string, filters:Record<string,unknown>={}) { if (env.DATA_MODE !== 'supabase' || !supabase) return null; let query=supabase.from(table).select('*'); for(const [key,value] of Object.entries(filters)) query=query.eq(key,value); const {data,error}=await query; if(error) throw error; return data; }
