import { createHash, randomInt, randomUUID, timingSafeEqual } from 'node:crypto';
import { env } from '../config/env.js';
import { store, supabaseInsert } from '../db/store.js';
import { AppError } from '../utils/http.js';
export const normalizePhone = (input:string) => { const digits=input.replace(/[^\d+]/g,''); const normalized=digits.startsWith('+')?digits:`+91${digits}`; if(!/^\+[1-9]\d{9,14}$/.test(normalized)) throw new AppError(400,'INVALID_PHONE','Enter a valid international phone number.'); return normalized; };
const hashOtp=(otp:string)=>createHash('sha256').update(`${otp}:${env.OTP_PEPPER}`).digest('hex');
export interface SmsProvider { sendOtp(phone:string, otp:string):Promise<void>; sendMessage(phone:string,message:string):Promise<void>; }
class ConsoleSmsProvider implements SmsProvider { async sendOtp(phone:string,_otp:string){ if(env.NODE_ENV==='production') throw new AppError(503,'SMS_NOT_CONFIGURED','An SMS provider is not configured.'); console.info(`[sms:console] OTP delivery requested for ${phone}; OTP is intentionally not returned by the API.`); } async sendMessage(){ throw new AppError(503,'SMS_NOT_CONFIGURED','A real SMS provider is not configured.'); } }
class TwilioProvider implements SmsProvider { private async send(phone:string,message:string){ if(!env.SMS_ACCOUNT_SID||!env.SMS_AUTH_TOKEN||!env.SMS_FROM_NUMBER) throw new AppError(503,'SMS_NOT_CONFIGURED','Twilio configuration is incomplete.'); const auth=Buffer.from(`${env.SMS_ACCOUNT_SID}:${env.SMS_AUTH_TOKEN}`).toString('base64'); const body=new URLSearchParams({To:phone,From:env.SMS_FROM_NUMBER,Body:message}); const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${env.SMS_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body}); if(!response.ok) throw new AppError(502,'SMS_DELIVERY_FAILED','The message could not be delivered.'); } async sendOtp(phone:string,otp:string){ await this.send(phone,`Your SAATH verification code is ${otp}. It expires in 5 minutes.`); } async sendMessage(phone:string,message:string){ await this.send(phone,message); } }
export const smsProvider:SmsProvider = env.SMS_PROVIDER.toLowerCase()==='twilio' ? new TwilioProvider() : new ConsoleSmsProvider();
export const smsProviderConfigured = env.SMS_PROVIDER.toLowerCase()==='twilio';
export async function requestOtp(phoneInput:string){ const phone=normalizePhone(phoneInput); const now=Date.now(); const active=[...store.otp.values()].find(x=>x.phone===phone&&!x.used&&x.createdAt+env.OTP_RESEND_COOLDOWN_SECONDS*1000>now); if(active) throw new AppError(429,'OTP_RESEND_COOLDOWN','Please wait before requesting another code.'); const otp=String(randomInt(100000,1000000)); const challenge={id:randomUUID(),phone,hash:hashOtp(otp),expiresAt:now+env.OTP_TTL_SECONDS*1000,attempts:0,used:false,createdAt:now}; store.otp.set(challenge.id,challenge); await supabaseInsert('otp_challenges',{id:challenge.id,phone_e164:phone,otp_hash:challenge.hash,expires_at:new Date(challenge.expiresAt).toISOString(),attempts:0}); await smsProvider.sendOtp(phone,otp); return {challengeId:challenge.id,expiresInSeconds:env.OTP_TTL_SECONDS}; }
export function verifyOtp(challengeId:string, otp:string){ const challenge=store.otp.get(challengeId); if(!challenge) throw new AppError(400,'OTP_NOT_FOUND','The verification request was not found.'); if(challenge.used) throw new AppError(400,'OTP_USED','This verification code has already been used.'); if(Date.now()>challenge.expiresAt) throw new AppError(400,'OTP_EXPIRED','The OTP has expired.'); if(challenge.attempts>=env.OTP_MAX_ATTEMPTS) throw new AppError(429,'OTP_ATTEMPTS_EXCEEDED','Too many incorrect attempts.'); challenge.attempts++; const actual=Buffer.from(hashOtp(otp)); const expected=Buffer.from(challenge.hash); if(actual.length!==expected.length||!timingSafeEqual(actual,expected)) throw new AppError(400,'OTP_INVALID','The verification code is invalid.'); challenge.used=true; return challenge; }
