"use client";

import Link from "next/link";
import { ArrowRight, CalendarDays, Check, CloudDrizzle, CloudRain, CloudSun, Heart, Leaf, Mic2, ShieldCheck, Sun, Wind } from "lucide-react";
import { useEffect, useState } from "react";
import { useAppStore } from "@/store/useAppStore";
import { caseService } from "@/services/case";
import { aiService } from "@/services/ai";
import { CaseRecord } from "@/types";
import { formatDate } from "@/lib/utils";
import { TAARA } from "@/components/TAARA";

const moods = [
  { key: "light", icon: CloudDrizzle, tone: "bg-[#e6f1ee] text-[#227d76]" },
  { key: "heavy", icon: CloudRain, tone: "bg-[#fff1dc] text-[#bd7927]" },
  { key: "veryHeavy", icon: CloudSun, tone: "bg-[#f7e4df] text-[#ac6353]" },
  { key: "okay", icon: Sun, tone: "bg-[#e5eddc] text-[#628062]" },
] as const;
const moodScores = { light: 2, heavy: 3, veryHeavy: 4, okay: 5 };

export default function SurvivorHomePage() {
  const { victimToken, survivorName, language } = useAppStore();
  const [caseRecord, setCaseRecord] = useState<CaseRecord | null>(null);
  const [selectedMood, setSelectedMood] = useState<string | null>(null);
  const hindi = language === "Hindi";
  const copy = hindi ? {
    greeting: "नमस्ते", enough: "आप यहाँ हैं। इतना काफ़ी है।", private: "आपकी जगह निजी और आपकी सहमति के अनुसार है", checkin: "आज आप कैसा महसूस कर रहे हैं?", noWrong: "यहाँ कोई सही या गलत जवाब नहीं है। बस जो सच है, उसे महसूस करें।", moods: { light: "थोड़ा भारी", heavy: "कुछ ज़्यादा भारी", veryHeavy: "बहुत भारी", okay: "मैं ठीक हूँ" }, selected: "चुना गया", continue: "चेक-इन जारी रखें", care: "आपके लिए कुछ", careText: "दो मिनट रुककर एक शांत गतिविधि करें।", way: "अपने तरीके से चेक-इन", wayText: "टेक्स्ट, आवाज़ या IVRS में से जो सहज लगे चुनें।", case: "आपका केस", connect: "केस कनेक्ट करें", hearing: "अगली सुनवाई", support: "आपकी सहायता टीम आपके साथ है", privacy: "आपकी पसंद, सहमति और गोपनीयता नियंत्रण हमेशा आपके पास हैं", demo: "सिंथेटिक डेमो डेटा" } : {
    greeting: new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening", enough: "You’re here. That’s enough.", private: "Your space is private and consent-first", checkin: "How are things feeling today?", noWrong: "There are no right or wrong answers. Just notice what is true.", moods: { light: "A little heavy", heavy: "Somewhat heavy", veryHeavy: "Very heavy", okay: "I’m feeling okay" }, selected: "Selected", continue: "Continue check-in", care: "Something for you", careText: "Take two minutes to slow down with a gentle grounding activity.", way: "Check in your way", wayText: "Text, voice, or IVRS. Choose what feels most comfortable today.", case: "Your case", connect: "Connect your case", hearing: "Next hearing", support: "Your support team is with you", privacy: "Your choices, consent, and privacy controls are always visible.", demo: "Synthetic demonstration data" };

  useEffect(() => { if (victimToken) caseService.getCase(victimToken).then((c: CaseRecord | null) => setCaseRecord(c)); }, [victimToken]);
  const [monitoring, setMonitoring] = useState<{ score: number | null; confidence: number; trend: string; insufficientEvidence: boolean } | null>(null);
  useEffect(() => { if (victimToken) aiService.getMonitoring("distress").then((m: any) => setMonitoring(m)); }, [victimToken]);
  const displayName = survivorName?.trim() || caseRecord?.survivorName?.trim();

  return <div className="px-5 pb-8 md:px-10 md:pb-14 xl:px-14">
    <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="font-display text-[42px] leading-[.98] text-text-primary md:text-[56px]">{copy.greeting}{displayName ? `, ${displayName}` : ""}</h1><p className="mt-4 text-lg text-text-secondary">{copy.enough}</p></div><div className="hidden items-center gap-2 text-xs text-text-secondary md:flex"><span className="h-2 w-2 rounded-full bg-sage" /> {copy.private}</div></div>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(330px,.75fr)]"><section className="space-y-5">
      <div className="surface overflow-hidden rounded-[28px] p-6 md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-text-secondary">{copy.checkin}</p><h2 className="mt-3 font-display text-3xl text-text-primary md:text-[36px]">{copy.checkin}</h2><p className="mt-2 text-sm text-text-secondary">{copy.noWrong}</p></div><Link href="/survivor/check-in" aria-label={copy.continue} title={copy.continue} className="hidden h-12 w-12 items-center justify-center rounded-2xl bg-greenish-cream text-deep-teal hover:bg-pale-sage md:flex"><Heart size={21} /></Link></div><div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{moods.map(({ key, icon: Icon, tone }) => <button key={key} onClick={() => { setSelectedMood(key); void aiService.submitQuickMood(moodScores[key], copy.moods[key]); }} className={`group rounded-2xl border p-4 text-left ${selectedMood === key ? "border-deep-teal bg-pale-sage/40 ring-4 ring-deep-teal/10" : "border-border-color bg-white hover:-translate-y-0.5 hover:border-soft-teal"}`}><span className={`mb-5 inline-flex h-10 w-10 items-center justify-center rounded-full ${tone}`}><Icon size={19} /></span><span className="block text-sm font-semibold leading-tight text-text-primary">{copy.moods[key]}</span>{selectedMood === key && <span className="mt-2 flex items-center gap-1 text-[11px] font-bold text-deep-teal"><Check size={13} /> {copy.selected}</span>}</button>)}</div>{selectedMood && <div className="mt-5 flex items-center justify-between rounded-2xl bg-greenish-cream px-4 py-3 text-sm text-text-secondary"><span>{copy.noWrong}</span><Link href="/survivor/check-in" className="ml-3 whitespace-nowrap font-bold text-deep-teal">{copy.continue} <ArrowRight className="ml-1 inline" size={14} /></Link></div>}</div>
      <div className="grid grid-cols-1 gap-5 md:grid-cols-2"><Link href="/survivor/feel-better" className="surface-soft group rounded-[26px] p-6 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-deep-teal shadow-sm"><Wind size={19} /></div><ArrowRight size={18} /></div><h3 className="mt-6 font-display text-2xl text-text-primary">{copy.care}</h3><p className="mt-2 text-sm leading-relaxed text-text-secondary">{copy.careText}</p></Link><Link href="/survivor/check-in" className="surface-soft group rounded-[26px] bg-[#fff4e9] p-6 hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-[#b97942] shadow-sm"><Mic2 size={19} /></div><ArrowRight size={18} /></div><h3 className="mt-6 font-display text-2xl text-[#503d31]">{copy.way}</h3><p className="mt-2 text-sm leading-relaxed text-[#7e6656]">{copy.wayText}</p></Link></div>
    </section><aside className="space-y-5"><TAARA /><div className="surface rounded-[26px] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-text-secondary">{copy.case}</p>{caseRecord ? <p className="mt-2 font-mono text-sm font-semibold text-text-primary">{caseRecord.docket}</p> : <p className="mt-2 text-sm text-text-secondary">{copy.connect}</p>}</div><Link href="/survivor/case" aria-label={copy.case} className="rounded-full p-2 text-text-secondary hover:bg-greenish-cream hover:text-deep-teal"><ArrowRight size={18} /></Link></div>{caseRecord && <><div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#eef6ef] p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#d2e9d5] text-[#488056]"><Leaf size={17} /></span><div><p className="text-sm font-semibold text-[#3f604a]">{caseRecord.currentStage}</p><p className="mt-0.5 text-xs text-[#718879]">{copy.support}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-border-color pt-4"><div className="flex items-center gap-2 text-xs text-text-secondary"><CalendarDays size={15} /> {copy.hearing}</div><span className="text-sm font-bold text-text-primary">{caseRecord.nextHearingDate ? formatDate(caseRecord.nextHearingDate) : "—"}</span></div></>}</div>
    {monitoring && <div className="surface rounded-[26px] p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-text-secondary">Wellbeing Status</p><p className="mt-2 text-sm text-text-primary">{monitoring.insufficientEvidence ? "Insufficient evidence" : `Distress score: ${monitoring.score}`}</p></div>}
    <div className="flex items-center gap-3 px-2 text-xs leading-relaxed text-text-secondary"><ShieldCheck size={16} className="shrink-0 text-sage" /> {copy.privacy}</div><div className="flex items-center gap-2 px-2 text-xs text-text-secondary"><Leaf size={13} /> {copy.demo}</div></aside></div>
  </div>;
}
