"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CircleAlert, ShieldAlert } from "lucide-react";

const alerts = [
  { id: "A-204", level: "P2", title: "Meaningful change detected", caseName: "Sunita", docket: "NHAA-RJ-2026-004821", reason: "Sleep disturbance increased; engagement decreased", confidence: "Moderate", lastContact: "3 days ago" },
  { id: "A-198", level: "P3", title: "Follow-up due", caseName: "Priya", docket: "NHAA-MH-2026-011932", reason: "Scheduled check-in has not been completed", confidence: "Low", lastContact: "6 days ago" },
  { id: "A-191", level: "P1", title: "Recent safety concern", caseName: "Anjali", docket: "NHAA-UP-2026-007765", reason: "Safety response changed across two check-ins", confidence: "Moderate", lastContact: "Yesterday" },
];

export default function CounsellorAlertsPage() {
  const [tab, setTab] = useState("New");
  const [reviewed, setReviewed] = useState<string[]>([]);
  const visible = alerts.filter((alert) => tab === "New" ? !reviewed.includes(alert.id) : tab === "Reviewed" ? reviewed.includes(alert.id) : alert.level === "P1");

  return <div className="mx-auto max-w-7xl space-y-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-deep-teal">Counsellor workspace</p><h1 className="mt-2 text-3xl font-semibold">Alerts</h1><p className="mt-2 text-sm text-text-secondary">AI-assisted early-support signals for human review. An alert is not a diagnosis.</p></div><div className="flex gap-2 border-b border-border-color">{["New", "Reviewed", "Critical"].map((name) => <button key={name} onClick={() => setTab(name)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === name ? "border-deep-teal text-deep-teal" : "border-transparent text-text-secondary"}`}>{name}</button>)}</div><div className="grid gap-4">{visible.length ? visible.map((alert) => <article key={alert.id} className="surface rounded-2xl p-5 md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div className="flex gap-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${alert.level === "P1" ? "bg-warm-peach/25 text-[#a15f4e]" : "bg-[#fff1dc] text-[#9b6e25]"}`}>{alert.level === "P1" ? <ShieldAlert size={21} /> : <CircleAlert size={21} />}</span><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-warm-peach/20 px-2 py-1 text-[11px] font-bold text-[#a15f4e]">{alert.level}</span><h2 className="font-semibold">{alert.title}</h2></div><p className="mt-2 text-sm text-text-secondary">{alert.caseName} · <span className="font-mono">{alert.docket}</span></p></div></div><div className="flex gap-2"><Link href={`/counsellor/cases/${alert.id === "A-204" ? "VIC_8291" : alert.id === "A-198" ? "VIC_4410" : "VIC_1173"}`} className="inline-flex items-center gap-2 rounded-lg bg-deep-teal px-3 py-2 text-xs font-bold text-white">Review case <ArrowRight size={14} /></Link><button onClick={() => setReviewed((current) => [...current, alert.id])} className="inline-flex items-center gap-2 rounded-lg border border-border-color px-3 py-2 text-xs font-bold text-text-secondary"><Check size={14} /> Mark reviewed</button></div></div><div className="mt-5 grid gap-3 rounded-xl bg-greenish-cream p-4 text-sm md:grid-cols-3"><div><p className="text-xs text-text-secondary">Contributing signals</p><p className="mt-1 font-medium">{alert.reason}</p></div><div><p className="text-xs text-text-secondary">Confidence</p><p className="mt-1 font-medium">{alert.confidence}</p></div><div><p className="text-xs text-text-secondary">Last human contact</p><p className="mt-1 font-medium">{alert.lastContact}</p></div></div></article>) : <div className="rounded-2xl border border-dashed border-border-color p-12 text-center text-sm text-text-secondary">No alerts in this view.</div>}</div></div>;
}
