"use client";
import Link from "next/link";
import { ArrowRight, BookOpen, Ear, Heart, Leaf, Moon, Play, Sparkles, Wind } from "lucide-react";
const activities = [
  { href: "/survivor/breathe", icon: Wind, title: "Breathe", desc: "A gentle rhythm to help your body soften.", time: "2 min", tone: "bg-[#e5f2ec] text-[#327d70]" },
  { href: "/survivor/ground", icon: Leaf, title: "Ground", desc: "Notice what is around you, one sense at a time.", time: "3 min", tone: "bg-[#f2ecd9] text-[#a47730]" },
  { href: "/survivor/relax", icon: Moon, title: "Relax", desc: "A guided pause for a busy or tired mind.", time: "5 min", tone: "bg-[#eee8f5] text-[#8064a2]" },
  { href: "/survivor/listen", icon: Ear, title: "Listen", desc: "Soft audio spaces for whenever words feel too much.", time: "4 min", tone: "bg-[#f9e9e3] text-[#b26b55]" },
  { href: "/survivor/just-stay", icon: Sparkles, title: "Just Stay", desc: "You do not have to talk right now.", time: "Open space", tone: "bg-[#dcebdd] text-[#0f766e]" },
  { href: "/survivor/understand", icon: BookOpen, title: "Understand", desc: "Small, plain-language guides for hard days.", time: "Read or listen", tone: "bg-[#e5eef5] text-[#5b8db8]" },
];
export default function FeelBetterPage() { return <div className="px-5 pb-10 md:px-10 xl:px-14"><div className="saath-fade max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#7e918b]">Feel better</p><h1 className="mt-3 font-display text-5xl leading-none text-[#172326] md:text-6xl">A little more room to breathe.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-[#63736e]">Choose something that feels possible right now. You can stop at any time — nothing here needs to be completed.</p></div><div className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{activities.map(({ href, icon: Icon, title, desc, time, tone }) => <Link href={href} key={title} className="surface group rounded-[26px] p-6 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-start justify-between"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${tone}`}><Icon size={22} /></span><ArrowRight size={18} className="text-[#9aaba4] transition-transform group-hover:translate-x-1" /></div><h2 className="mt-7 font-display text-2xl text-[#243630]">{title}</h2><p className="mt-2 min-h-12 text-sm leading-relaxed text-[#6b7b75]">{desc}</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-[#0f766e]"><Play size={13} /> {time}</div></Link>)}</div><div className="mt-8 rounded-[26px] bg-[#0f766e] p-6 text-white md:flex md:items-center md:justify-between md:p-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#bde5d1]">TAARA says</p><p className="mt-3 font-display text-2xl">“I&apos;m here when you&apos;re ready.”</p></div><Link href="/survivor/taara" className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-[#0f766e] md:mt-0">Open quiet space <ArrowRight size={16} /></Link></div></div>; }
